### ISSUE TITLE
Adding BIDS support

### ISSUE THREAD

**Issue by chrisfilo** [MonashBI/arcana#47]
- Extension of `LocalRepository`
- Specify which `kwargs` need to be specified for each `Study` field. Those could be passed to pybids queries. Alternatively use a function pointer with `BIDSLayout` argument passed for more complex queries (think fieldmaps).

More on pybids: https://github.com/INCF/pybids/tree/master/bids/grabbids

**Comment by tclose** [comment]
BIDS support has been added to MonashBI/banana now instead

**Comment by chrisfilo** [comment]
Awesome!
